name: Build npm release

trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - "*"

jobs:
  # Need windows-2019 to do esy import/export-dependencies
  # which assumes you have bsdtar (tar.exe) in your system
  # otherwise it will end up using the esy-bash tar which doesn't
  # understand drives like D:/ (thinks it's an scp path).
  - template: .ci/build-platform.yml
    parameters:
      platform: Windows
      vmImage: windows-2019
